### ISSUE TITLE
Any newlines are not preserved while editing text fields in "Database" tab

### ISSUE THREAD

**Issue by GavanWilhite** [nhost/nhost#1030]
If you enter a newline character into the field, it will first appear visible, but will be removed when saved / restored.

For context, the behavior in the Hasura dashboard is that newlines are not supported when editing inline, but if you expand the text field, newlines are supported.

**Comment by elitan** [comment]
Do you mean that `\n` is automatically converted to an actual new line in our dashboard? And you would expect that when inserting `\n` you would also see the `\n` in the textarea instead of converting it to a new line?


https://user-images.githubusercontent.com/331818/195774902-57386a7f-17f2-4770-a5a2-e4d9a3ddd331.mp4

**Comment by GavanWilhite** [comment]
I specifically mean that hitting the “Return” key on the keyboard visually
enters a newline, but that the newline does not survive entry into the DB.

**Comment by elitan** [comment]
Hitting the "return" key means you save. You need to do shift+enter to do a new line.
