### ISSUE TITLE
MySQL Preview

### ISSUE THREAD

**Issue by simonphughes** [nhost/nhost#1047]
Is there any way to currently use the open source hosted version of nhost with the MySQL Preview of Hasura?

**Comment by plmercereau** [comment]
Hello,

It would require significant adjustments to our authentication and storage services, in addition to hasura. This is not on the roadmap.

That being said, the MySQL preview still uses Postgres to store Hasura metadata, so it could be adjusted so Postgres is still used as the default database for metadata, auth and storage, but to add a second MySQL DB source, as Hasura supports multiple sources since 2.0.

Let us know if you try it and what you could learn from it, other users may be interested!

**Comment by simonphughes** [comment]
Thats exactly what I was thinking, using Postgres to store the metadata and auth tables and then adding in a second data source of MySQl. Assuming this isn't going to be supported in the hosted version any time soon, I'll try self hosting and deploy the preview of Hasura.  I'll report back how it goes in the next week just in case any one else is interested.

**Comment by plmercereau** [comment]
When the MySQL feature will be more mature (when it will be included in the Hasura version we are shipping), it will become possible to connect an additional DB through the Hasura console with its connection string. For the moment the feature is only available on a versioned Hasura docker image.
You would then need to host the MySQL DB somewhere and that's it!

Keep us posted!
