### ISSUE TITLE
Custom email templates from the Nhost console

### ISSUE THREAD

**Issue by plmercereau** [nhost/nhost#120]
In Hasura-auth, it is possible to define custom email templates, but it is not possible yet to configure and deploy them from the Nhost console or CLI.
@alveshelio et al. would be pleased to get this feature.
See [this issue](https://github.com/nhost/hasura-auth/issues/74) for follow-up.

**Comment by alveshelio** [comment]
@plmercereau When would this be available in Nhost console? Will we be able to define templates by locale? What kind of templates do you support? Only HTML templates? Right now we are working with MJML from https://mjml.io/ It can spit out html though.

**Comment by plmercereau** [comment]
No date is set yet, sorry about that.
MJML templates could be easily implemented in hasura-auth as [the library we're using can use custom template engines](https://github.com/forwardemail/email-templates#custom-template-engine-eg-ejs). Contributions welcome!
That being said, it won't solve this current issue :)

**Comment by alveshelio** [comment]
In the meantime how could we solve this issue? We are about to go in production and the current email template isn't an option. Since this issue: https://github.com/nhost/hasura-auth/issues/74 has been closed what are your suggestions to have this ASAP?

**Comment by MaxSchilling** [comment]
Html templates / or any other customizable format would be sufficient. I agree that the verification should/must still be possible and shouldn‘t be bypassed, but the standard anonymus „template“ (lets face it, its a three liner…), as it is right now has to be changeable. It‘s even less text then in v1 and at least there I was able to change the text around the verification link. Now I would have to send english confirmations to german users..? Plus, our users wouldn‘t even understand the connection to our app, noone of our users knows nhost.. Pretty sure those emails will be handled as spam anyway soon without any proper texts? 
Is there really no other way??
I don‘t see any production fit like that and expected more from v2 tbh…

**Comment by alveshelio** [comment]
Salut @plmercereau comment ça va :)

Regarding your comment on the other issue you've posted:

> If I understood well, you want the client to be able to get the email verification ticket without sending the email. In this case, it defeats the purpose of email verification, and I would rather allow users to authenticate without verification in setting AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED to false.
Unless I misunderstood, we won't implement this approach and I'm therefore closing this issue.

You've misunderstood what I'm trying to achieve, this is not what I want. What I want is to be able to use my own email provider and email template. Right now I'm allowing users to authenticating without sending the verification email and I'm then sending the verification email myself using `nhost.auth.sendVerificationEmail()`, however, what I'd like to do is to be able to use my email templates because the ones offered by Nhost are not ready for production.

So what I'd like instead is to be able to pass an option to these endpoints that automatically send an email, that would prevent the email from being send and would instead return the url generated so I could use it to then send an email using my email templates instead.

This would have no impact on users who want to use Nhost email provider and email templates and would give users the flexibility to choose what to do.

**Comment by plmercereau** [comment]
Hello @alveshelio,
- We talked end of last week about giving more clarity on when we would work on it. ETA is one/two months
- In the meantime, I drafter a small workaround based on a serveless function: [here's the repo](https://github.com/plmercereau/nhost-custom-email-verification). I stopped coding where you should then contact your custom email/template provider.

Design:
1. Deactivate Nhost/Hasura-auth sending email verification
2. a user signs up email+password. Current behaviour is that email is unverified but ticket is generated
3. a Hasura event triggers a serveless function on every user creation/update (field listened to: ticket)
4. the serverless function gets the user context including email and ticket
5. you can now define your own logic to send a custom email

I hope it will help while waiting for a all-included solution

**Comment by alveshelio** [comment]
HI @plmercereau,

Thank you for taking the time for replying.
This workaround only works for email verification when a user create his account. How about when the user forgot his email? How about other endpoints that automatically sends an email through Nhost with his email template?

I don't see the problem to add an option to these endpoints that would allow us to handle email on our side. You guys are assuming we want to use your email server but we might want to use ours. How can you ensure that all the emails will be delivered?

Another point is that I don't want my emails to be sent through the email address  **noreply@nhost.app**, can this be configured to be sent through our email address?

It seems that I'd be forced to fork this repo and do my own modifications if you guys are not willing to do so. We are about to lunch and we cannot wait 2 months and the solution you've provided only works for email verification.

Thank you

**Comment by MaxSchilling** [comment]
Another thing to add, as written in Discord, the success message for requesting changes / verifying the e-mail/ etc. should be changeable as well to be adopted to the company CI instead of an standard English text one liner in a white blank browser window (like in v1). This would round everything up.

**Comment by elitan** [comment]
This is now possible. 

https://docs.nhost.io/platform/authentication/email-templates#enabling-custom-email-templates

We're also working on ways to improve this workflow. Stay tuned! :)

**Comment by dohomi** [comment]
@elitan I am not sure but the issue states that Nhost console should be able to change the emails. I think if that is only enabled via CLI its very developer centric. I don't think that in a project the developer should handle email templates, mostly this is another person. In a client project I have to go back and forth with the person in charge who wants to make changes to the emails.

It would be ideal (especially in PRO plan) if emails can be edited inside the Nhost console that not only the developer can make changes. I would love to see that being possible inside the settings => emails tab

**Comment by dbarrosop** [comment]
@dohomi I'd suggest opening a new issue so it can be treated as a new feature request

**Comment by dohomi** [comment]
#1842
