### ISSUE TITLE
Can't delete a created bucket by hasura dashboard

### ISSUE THREAD

**Issue by Nico-L** [nhost/nhost#121]
Hello,

If I create a new bucket in the storage part of Hasura with a specified id, I see the following:
* when I browse rows of the buckets table ( storage>buckets>Browse Rows), each bucket shows a NULL id but I can upload files to the new bucket with the javascript SDK
* when I try to delete the newly created bucket I have an error saying that I can't delete the default bucket (I am sure that this is not the default bucket).

This is happening for two different project I set up in nhost

Maybe I do not create a bucket the right way?

Thanks

**Comment by elitan** [comment]
It's because of this issue:

https://github.com/hasura/graphql-engine/issues/8020

Basically, the Hausra console does not render data correctly because we've set the GraphQL field for `id` to be `id`. Similar to how we do it in Hasura Auth here: 

https://github.com/nhost/hasura-auth/blob/main/src/metadata.ts#L212

Until this is fixed in the Hasura console, you can use SQL to edit this:

```
SELECT * FROM storage.buckets;
DELETE FROM storage.buckets WHERE id = '';
```

**Comment by Nico-L** [comment]
Thnaks @elitan. I'll use SQL.
