### ISSUE TITLE
[self-hosted] [docker-compose] dashboard fails to create table

### ISSUE THREAD

**Issue by kingdevnl** [nhost/nhost#1220]
`POST http://localhost:9693/apis/migrate net::ERR_CONNECTION_REFUSED`

There is no service listening on port 9693

**Comment by szilarddoro** [comment]
Something is likely missing from the docker-compose example @plmercereau. We use a different configuration for our backend here than the one we use to run the services through the CLI. I assume some port configuration is missing here, which is not necessarily related to the dashboard.

We allow the configuration of several ports through the following environment variables:
`NEXT_PUBLIC_NHOST_LOCAL_BACKEND_PORT` - Port of the locally running backend.
`NEXT_PUBLIC_NHOST_LOCAL_HASURA_PORT` - Port of the locally running Hasura Console.
`NEXT_PUBLIC_NHOST_LOCAL_MIGRATIONS_PORT` - Port of the locally running migrations API.

I followed the steps in the docker-compose example's README, but I couldn't start the example project to test this.

**Comment by plmercereau** [comment]
The environment variables are fine, the problem was that the way the local dashboard is configured, it always requires the hasura console to run from the hasura cli to work (or I missed something)
I updated the example https://github.com/nhost/nhost/pull/1231

That being said, it could be nice that the dashboard could work in the following setups:
- [x] using the Nhost CLI, with the local migrations/metadata tracking
- [x] in the Nhost Cloud
- [x] use on localhost (the example)
- [ ] use on any host, with the local hasura console for migrations/metadata tracking (could work)
- [ ] use on localhost/any host without the hasura console, similar to an app in the Nhost cloud

**Comment by szilarddoro** [comment]
> it always requires the hasura console to run from the hasura cli to work (or I missed something)

The dashboard can now be used for **local** development. We allow this by connecting it to a **local** environment. It needs a service to listen on `localhost` on port `9693` by default. It doesn't exactly need Hasura Console, but Hasura's migrations service to listen either on the default port or a port specified by the user. If it's a custom port, then it needs to be set through the `NEXT_PUBLIC_NHOST_LOCAL_MIGRATIONS_PORT` environment variable for the dashboard.

At the moment we don't support authentication and a few pages (logs, functions, settings, etc.) that are available on the cloud version when the dashboard is not connected to our platform, so self-hosting is not necessarily recommended in my opinion.

Maybe I'm missing something here, but this is not a near-term use case for the dashboard as far as I'm concerned.
@elitan please correct me if I'm wrong.

**Comment by elitan** [comment]
Yea, for now, it's required to run `hasura console` for the Nhost Dashboard to work.

**Comment by LeulAria** [comment]
can't we use
https://hasura.io/docs/latest/hasura-cli/commands/hasura_console/

```
hasura console --endpoint <container network endpoint, like: http://host.docker.internal:8080> --no-browser --address 0.0.0.0 --console-hge-endpoint http://0.0.0.0:8080

hasura console --address <address> --console-port 9090 --api-port 9091
```
