### ISSUE TITLE
Export nhost.auth methods for useNhostAuth hook of react-auth

### ISSUE THREAD

**Issue by dohomi** [nhost/nhost#127]
Hello

I just give the new v2 of Nhost a spin and I am quite excited about all the new functionalities. 

It would be great if the hook `useNhostAuth` would also export `nhost.auth` logic. This would `hookify` the user experience.
 
```ts
  const { user, isAuthenticated, isLoading, auth: { getAccessToken } } = useNhostAuth() // I would like to be able to access auth methods of nhost   
```

**Comment by elitan** [comment]
Yea I see your point. The idea with `useNhostAuth` hook is to trigger re-render on auth state updates and not specifically to access the `auth` object. Maybe the naming of the hook could be better to indicate its purpose?

Any specific reason why you want to also access the `auth` object in the hook? Rather than importing the `nhost` instance?

**Comment by dohomi** [comment]
@elitan I opened this issue on the SDK itself: https://github.com/nhost/nhost-js/issues/23

Its mainly about tree-shakable and reducing the numbers of imports. I think the react hooks could expose the instance of `nhost.auth` and more on the hook level. Its just an idea of keeping it more the React hook way of doing things.

**Comment by plmercereau** [comment]
All the authentication-related methods have been hookified with the release of the new [@nhost/react package](https://github.com/nhost/nhost/releases/tag/%40nhost%2Freact%400.2.0).

See also 
https://docs.nhost.io/reference/react
