### ISSUE TITLE
Nhost Dashboard behave differently in light and dark theme

### ISSUE THREAD

**Issue by lokeswaran-aj** [nhost/nhost#1706]
**Describe the bug**
The Docs and profile icon position itself in the center in the light theme and on the right in the dark theme in the Dashboard. There is a hamburger icon on the right in the light theme without opening any menu.
*Light theme*
<img width="1494" alt="Screenshot 2023-03-05 at 9 18 43 PM" src="https://user-images.githubusercontent.com/74011196/222970872-336db4c3-8673-48b0-aced-f393335da355.png">

*Dark Theme*
<img width="1496" alt="Screenshot 2023-03-05 at 9 19 22 PM" src="https://user-images.githubusercontent.com/74011196/222970909-7cdc49dd-d5ec-41e2-9925-92524204905c.png">
Someone, please confirm if this is happening only to me.
**To Reproduce**
1. Follow the [DEVELOPERS.md](https://github.com/nhost/nhost/blob/main/DEVELOPERS.md) and run the [react-apollo example](https://github.com/nhost/nhost/blob/main/examples/react-apollo/README.md).
2. Open the Nhost dashboard.

**Expected behavior**
The Docs and profile icon should be on the right in the light theme

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Chrome

**Comment by szilarddoro** [comment]
I tried reproducing this issue using the same dashboard version (`0.11.17`) with no luck. I'd be surprised if this would be caused by switching between light and dark modes considering that there are no conditionally rendered elements for any of these themes. 

The only way I could reproduce this is by manually removing the `sm:hidden` class from the mobile menu's button. I don't see how that would be possible other than doing this by hand.

**Comment by lokeswaran-aj** [comment]
With the latest version, I also could not reproduce it. I guess all is good now👍
