### ISSUE TITLE
Any plans to add monitoring for Postgres?

### ISSUE THREAD

**Issue by viktorfa** [nhost/nhost#1710]
**Is your feature request related to a problem? Please describe.**
Analyzing the query times on your database is very useful when creating indexes and optimizing your queries. Seeing other stats like table sizes and the difference in table sizes over time can be useful to understand your app. 

**Describe the solution you'd like**
Include some query/db monitoring to Nhost. I'm not sure how feasible this is, but it would be useful.

**Describe alternatives you've considered**
I read about https://github.com/ankane/pghero and https://github.com/ankane/dexter to monitor Postgres and suggest indexes, respectively. Seems like you need to configure the logging of Postgres, which I'm not sure how to do in Nhost, but could probably be done by the Nhost team so that everyone gets it by default.
https://www.eversql.com/sensors/ is another similar solution.
Alternatively, you could write some guides on how to do this yourself in the DB docs of Nhost.

**Additional context**
Pghero demo
![image](https://user-images.githubusercontent.com/5357936/223330758-1de2219a-011a-454c-94e1-16d696caa6b8.png)

**Comment by ctrlemo** [comment]
Yes, I also would find it useful to be able to install extensions used by popular database monitoring tools

- https://pganalyze.com/docs/install/self_managed/02_enable_pg_stat_statements
- https://docs.datadoghq.com/database_monitoring/setup_postgres/selfhosted?tab=postgres10#configure-postgres-settings

Most of these APM or database monitoring tools require some sort of configuration change to postgres instance.
Since Nhost is a platform used by multiple users, doing this on an individual instance basis can become a bit to much. You should think about streamlining integration with these kind of 3rd party tools by offering like a specific section on the Nhost Dashboard where a user can select integration they would like to have enabled and automating the installation steps based on user provided inputs.

Not sure what the plans are related to offering database performance monitoring, but it is something most developers would love to have access to whenever they need to troubleshoot production database performance issues.

**Comment by dbarrosop** [comment]
We have plans for similar functionality but for the enterprise plan.

> but could probably be done by the Nhost team so that everyone gets it by default

Enabling this type of functionality has implications; more memory/CPU usage so potentially lower performance for the user and higher infra costs for us. So it isn't something that can be enabled for everybody by default and forget about it. However, we may be able to enable such functionality for you temporarily if you want to optimize your queries so feel free to reach out to me via DM with the exact config changes you need and I can enable them for you temporarily.

**Comment by dbarrosop** [comment]
Now that stale brings this to our attention. This should be doable now with [Nhost Run](https://docs.nhost.io/run)
