### ISSUE TITLE
Duration Refresh Token is valid for

### ISSUE THREAD

**Issue by simonphughes** [nhost/nhost#1717]
The refresh token that is currently issued by nhost allows the user to close the browser and come back again later and get a new JWT. We need to force a user to login every 24 hours. I can see from the code that it reads from an env variable called AUTH_REFRESH_TOKEN_EXPIRES_IN and has a default value which is far bigger then we require.

However if I try and go into the nhost dashboard and add the env variable with the name AUTH_REFRESH_TOKEN_EXPIRES_IN then it tells me I can't do that. Is there any way to override this and set it to 24 hours?

Thanks,

**Comment by wollerman** [comment]
Adding my vote for this issue. I also had started a discussion because I was unsure of how to extend the session. 

Someone in the discussion also pointed out the environment variable, but it can't be set in the nhost console because of the prefix.

Linked discussion: https://github.com/nhost/nhost/discussions/1890

**Comment by dbarrosop** [comment]
This will be configurable soon.

**Comment by szilarddoro** [comment]
This has been added to the settings page. You can go to **Settings** > **Authentication** > **Session** to configure it.
