### ISSUE TITLE
Forgot password or validate is slow

### ISSUE THREAD

**Issue by pedromontanes** [nhost/nhost#1850]
When i use the service forgot password or validate, the service that send the email has a delay of several minutes.. I has a premium account and the email configuration is in gmail.. (workspace service with custom domain).
how can I improve the email service  ?

**Comment by dbarrosop** [comment]
hasura-auth sends the email before the request is completed so any delays are on the SMTP server side so unless you can attribute it to hasura-auth somehow (like the request being frozen for several minutes, which I wouldn't expect so) I am afraid there isn't much we can do.

Closing as I don't think this is an issue on our side but feel free to comment/reopen otherwise.
