### ISSUE TITLE
PR proposition : SDK admin mode + impersonation

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#1908]
**Is your feature request related to a problem? Please describe.**
I have two use cases which required me to extend the Apollo Client:
1. In my serverless functions, I sometimes send queries / mutations as an admin (so x-hasura-admin secret set in the headers), or as the user by using impersonation (x-hasura-admin-secret + x-hasura-user-id + x-hasura-role set in headers).
2. I implemented an impersonation feature for my app. As a support team member, I can impersonate a user when I receive a support request

**Describe the solution you'd like**
I would like the Nhost SDK to expose those methods
* setAdminSecret(string): void
* impersonateUser(impersonateOptions: {userId: string, role?: string, [key:string]:string})
* isAdmin(): boolean
* isImpersonatingUser(): boolean

I would like those methods to be part of Nhost SDK and also the getHeaders method to take into account the impersonation / admin mode to return x-hasura-admin-secret + x-hasura-user-id + x-hasura-role set in headers.

**Describe alternatives you've considered**
Currently, I wrapped Nhost client and apollo client in a custom extended apollo client which has those methods:

**Comment by dbarrosop** [comment]
While I agree the functionality is interesting and useful I personally think we could implement this in a more generic way. Instead of adding more methods to the SDK targeting a this specific workflow what I'd propose is simply to allow attaching arbitrary headers to each method/request, that way you can send any combination of headers you want to implement whichever workflow you need/want to implement.
