### ISSUE TITLE
Upgrade to v1.0.4 has made breaking changes to local development and they aren't obvious

### ISSUE THREAD

**Issue by wollerman** [nhost/nhost#2013]
I just recently upgraded to v1.04 and wanted to report the breaking changes. The docs made it seem like a simple config change, but in fact there were a handful of things that are different. I'll enumerate them and the effects below:

* initially after upgrading the CLI I couldn't start anything because the commands have changed. The command is no longer `nhost dev` but instead `nhost up`. When using this I saw a message about the wrong hasura version. However it had pulled configs directly from the cloud instance. Eventually I found that there are only 4 different graphql engines and the one being recommend by the CLI (2.18.0) happened to not be tagged: https://hub.docker.com/r/nhost/graphql-engine/tags
* Just upgrading the CLI is not enough. It changes where things are run and there is no indication or output to highlight this. Before I could run `nhost dev` and it showed me the nice little helper, as indicated in the docs, where each URL exists. And before I could use `localhost:9695`. The first issue with this is I didn't know where to find the new local network names. Is there a replacement to `nhost dev` to see all the URLs like before?
* The second issue related to only upgrading the CLI is that my app started failing on local dev. It turns out I had to upgrade all of the NPM packages as well and then modify my local config to specify `subdomain` as `local` instead of `localhost`.
* The most jarring issue was that the new framework pulled new images and uses a different system to manage branch volumes. So all of my local test data was wiped.

Overall I'm super excited about all the new changes, but the config announcement made it seem like there wouldn't need to be any other migrations.

Hopefully highlighting these there can be a better community migration guide to warn individuals about upgrades and what to expect. That being said, after these hiccups the migration worked and the app is back up and humming! And all of these issues were with my local. Production had no issue and everything seemed just fine.

Thanks for all your hard work and let me know if I can clarify anything further.

**Comment by israelidanny** [comment]
Having some similar issues here:
https://github.com/nhost/cli/issues/720

**Comment by dbarrosop** [comment]
> The docs made it seem like a simple config change, but in fact there were a handful of things that are different

We tried to indicate there were breaking changes by following semver rules; i.e., we increased the major release version. But I agree we could've done a better job and list all the changes in one single place.

> the one being recommend by the CLI (2.18.0) 

I understand the confusion but the CLI is actually not recommending that version, it is indicating the new CLI won't work without at least that version (due to some hasura features the new CLI requires). In any case, I understand it is confusing so I think I will change the minimum version to avoid confusions.

> It changes where things are run and there is no indication or output to highlight this

I am afraid I don't understand this one. The output of `nhost up` should give you the URLs for all services:

```
Nhost development environment started.

URLs:
- Postgres:             postgres://postgres:postgres@localhost:5432/local
- Hasura:               https://local.hasura.nhost.run
- GraphQL:              https://local.graphql.nhost.run
- Auth:                 https://local.auth.nhost.run
- Storage:              https://local.storage.nhost.run
- Functions:            https://local.functions.nhost.run
- Dashboard:            https://local.dashboard.nhost.run
- Mailhog:              https://local.mailhog.nhost.run

SDK Configuration:
 Subdomain:             local
 Region:                (empty)

Run `nhost up` to reload the development environment
Run `nhost down` to stop the development environment
Run `nhost logs` to watch the logs
```

If you don't see this, please, share the output of `nhost up` so I can take a look.

> It turns out I had to upgrade all of the NPM packages as well and then modify my local config to specify subdomain as local instead of localhost.

Actually, using `localhost` was deprecated months ago. The SDK has been logging a warning about it since then and the CLI has been including the new information for a while too (as you can see in the output above but if you haven't updated your dependencies for months you may have missed that. All in all, we'd recommend you updating dependencies every now and then to ensure you get latest bugfixes.

> So all of my local test data was wiped

I understand this is frustrating. However, we discourage users from relying on data persisting between reboots. If you need test/development data we recommend using [seeds](https://docs.nhost.io/cli/seeds) instead as it's a more reliable way of initializing data (specially if you have multiple environments like development and testing or multiple developers)

Thanks a lot for the feedback, I really appreciate it and understand the frustration. This was a big upgrade with a lot of moving parts so I understand it can be a significant amount of work for some users. It is very hard to write ironclad documentation as different users struggle with different things, this time we tried to run the new CLI as a beta for a while to see where people were struggling and what things weren't working but understandably most Nhost users are as busy as we are so we didn't get as much feedback as we'd hope for.
