### ISSUE TITLE
Support App Router Nextjs 13 in nhost/nextjs package

### ISSUE THREAD

**Issue by suplere** [nhost/nhost#2104]
App Router is now in a stable version for NEXT.js. Are you planning to support App Router in the nhost/nextjs package? E.g. getNhostSession and createServerSideClient, require Context, but it is not available in App Router. Thank you for answer.

**Comment by dbarrosop** [comment]
Thanks for reporting this. We don't have immediate plans to support this as we have other priorities right now but we'd love to eventually. If someone in the community wants to step up and help with this we will be more than happy to provide guidance and review.

**Comment by suplere** [comment]
Hello all, you can try this repo https://github.com/suplere/nhost-auth-helpers - inspired from supabase. Please this is not final solution but first attempt.

**Comment by suplere** [comment]
I did some correction, and add to the app example recover password.

**Comment by suplere** [comment]
Hello, I have a look on your example. Your example uses data download and NHost usage only in Client Components.
How do you solve the initial session in the Provider? How can I use NHost in Server Components? How to use it in middleware? How to use NHost in Server Actions?

This is mainly about how to use NHost in "Server Components".

**Comment by suplere** [comment]
I'd rather see a similar modification of the library that would include these clients (two for the old Pages-based implementation, and the others for the new App structure):
Pages folder Api:
PageServerNHostClient
PageClientNHostClient

App folder API:
AppServerComponentClient
AppClientComponentClient
AppMiddlewareClient
AppRouteClient
AppServerActionClient

**Comment by onehassan** [comment]
The example is not complete, we are currently working on supporting RSCs. We will be making an abstraction similar to what you proposed once we have an general sense of what we need to do to support not only next.js but other frameworks as well

**Comment by fonksiyoneltip** [comment]
Damn. My projects update schedule is completely trashed now.

> Thanks for reporting this. We don't have immediate plans to support this as we have other priorities right now but we'd love to eventually. If someone in the community wants to step up and help with this we will be more than happy to provide guidance and review.

@dbarrosop, is what you said up there still valid? Any updates? And what would you suggest? 

Like, completely trashing `NhostProvider` and `hooks` and use the `NhostClient` and it's functions directly?

**Comment by dbarrosop** [comment]
@fonksiyoneltip I'd appreciate a bit of more calm and constructive feedback.

Not sure how us writing an initial example to show how to use the App Router "trashes" anyone schedule or makes anyone think that we are "trashing" anything. This example shows how to use something that people were struggling with because the existing hooks and functions didn't work due to the lack of Context.

If you have feedback about the proposed solution it is more than welcome. As Hassan mentioned in his previous comment, we are basically looking into writing examples for different frameworks with different constraints in order to gather info and feedback to build common abstractions, this has nothing to do with existing supported frameworks/mechanisms.

**Comment by anelad** [comment]
> @fonksiyoneltip I'd appreciate a bit of more calm and constructive feedback.
> 
> Not sure how us writing an initial example to show how to use the App Router "trashes" anyone schedule or makes anyone think that we are "trashing" anything. This example shows how to use something that people were struggling with because the existing hooks and functions didn't work due to the lack of Context.
> 
> If you have feedback about the proposed solution it is more than welcome. As Hassan mentioned in his previous comment, we are basically looking into writing examples for different frameworks with different constraints in order to gather info and feedback to build common abstractions, this has nothing to do with existing supported frameworks/mechanisms.

Sorry, I didn't mean any anger / bad reaction / blaming you or something. **You are not trashing anything.**. I'm not a native speaker so I might not able to take into account how you could take my words. I'm asking for your forgiveness and understanding on this.

By saying "trashed" just my plans got trashed by the current situation. Not by you though. You do not have to push immediate updates or even support NextJS, I completely understand and show respect you and your future plans.

I was just saying that the current situation affected our schedule. Planning to go for NextJS 13's app router has bad affected our codebase at the first place, far before your official support on it.

Should I quit using hooks or wait for upcoming updates, that's my only concern; so I just wanted simply ask you if you still do not feature immediate updates on @nhost/next-js

I hope I have expressed myself better this time. And I'm sorry again for causing misunderstanding with my wrong word choices. 🤝

**Comment by fonksiyoneltip** [comment]
> @fonksiyoneltip I'd appreciate a bit of more calm and constructive feedback.
> 
> Not sure how us writing an initial example to show how to use the App Router "trashes" anyone schedule or makes anyone think that we are "trashing" anything. This example shows how to use something that people were struggling with because the existing hooks and functions didn't work due to the lack of Context.
> 
> If you have feedback about the proposed solution it is more than welcome. As Hassan mentioned in his previous comment, we are basically looking into writing examples for different frameworks with different constraints in order to gather info and feedback to build common abstractions, this has nothing to do with existing supported frameworks/mechanisms.

Sorry, I didn't mean any anger / bad reaction / blaming you or something. **You are not trashing anything.**. I'm not a native speaker so I might not able to take into account how you could take my words. I'm asking for your forgiveness and understanding on this.

By saying "trashed" just my plans got trashed by the current situation. Not by you though. You do not have to push immediate updates or even support NextJS, I completely understand and show respect you and your future plans.

I was just saying that the current situation affected our schedule. Planning to go for NextJS 13's app router has bad affected our codebase at the first place, far before your official support on it.

Should I quit using hooks or wait for upcoming updates, that's my only concern; so I just wanted simply ask you if you still do not feature immediate updates on @nhost/next-js

I hope I have expressed myself better this time. And I'm sorry again for causing misunderstanding with my wrong word choices. 🤝

**Comment by dbarrosop** [comment]
No worries, no harm done :)

> Should I quit using hooks or wait for upcoming updates

I am not sure about the specifics of your application but anything that is working for you now will continue to do so. We are not planning to phase anything out or to make any breaking changes. What we are discussing here is how to support new stuff and it shouldn't affect anything that is working already.

**Comment by kelkes** [comment]
> The example is not complete, we are currently working on supporting RSCs. We will be making an abstraction similar to what you proposed once we have an general sense of what we need to do to support not only next.js but other frameworks as well

Sounds good. Any update on that? 

It does feel kinda wrong starting new projects with the pages router now. But the Nhost tooling is too good and i don't want to half-ass an app dir integration.

**Comment by dbarrosop** [comment]
the draft is here #2225, still WIP though

**Comment by onehassan** [comment]
We've just added a comprehensive project running Nhost with the new App Router and Server Components. Take a look [here](https://github.com/nhost/nhost/tree/main/examples/quickstarts).

If you have any feedback or suggestions please let us know.

**Comment by dbarrosop** [comment]
we are closing this one for now, if you have feedback don't hesitate to keep commenting.

**Comment by chrtze** [comment]
Hi @onehassan, thanks for adding this new example. It really made me understand more how we can get nhost to work with RSC in Next 13.  However, I did not manage to get it running properly. Some of my first findings are:

1. checking the auth status within the middleware sometimes causes very long loading times or even freezing the app. I think this is due to async requests being made in the middleware as the exported middleware function is called for every request. For example, in our app, it is even called for static assets which can lead to ~100 function calls for one request. I tried to prevent this by adding a [matcher config](https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher) so that the middleware only runs for protected routes.
2. For some reason, I couldn't get magic link to work. Somehow, the session cookie is not set properly when clicking the magic link. Not sure why this is happening as it is working in the sample app.
3. Usage in combination with React SDK: Our medium sized app uses the nhost provider and hooks in multiple places. I couldn't figure out a way to make this work so that the server components and the nhost provider share the same client. Does it mean that you would need to decide for one approach (either RSC or client hooks) or is there some way to make them coexist?
4. The implementation of this doesn't feel production-ready to me. I am not a backend developer and always liked to work with the nhost sdk because it didn't made me think about the backend logic that it handles. Maybe I am too concerned about this but I would be more confident if this logic would be baked into a sdk.

Again, thank you so much for providing this :) it helps us a lot!

**Comment by kelkes** [comment]
Hey, 

as more and more of my projects move to next.js app router (with next.js 14+15). Are there any plans to provide a more sophisticated integration? The example is nice, and I made it work somehow, but it's not on the same level of smoothness as the pages router integration provided.

Best,
David

**Comment by dbarrosop** [comment]
Not at this point, we don't have the cycles to support all frameworks and their many flavors, unfortunately. However, if people wants to contribute them we could arrange something.

**Comment by kelkes** [comment]
@dbarrosop Thanks for the clarification. I get that. Thanks

**Comment by moklick** [comment]
@dbarrosop It would be great if your team could have another look at this. Next.js app router is the [first thing in the official React documentation](https://react.dev/learn/creating-a-react-app#nextjs-app-router). It's the recommended way how to create a React app.

**Comment by dbarrosop** [comment]
We have an example using RSC and App router already:

https://github.com/nhost/nhost/tree/main/examples/quickstarts/nextjs-server-components

Or am I missing something here?
