### ISSUE TITLE
RFC: The ability to query enabled auth methods should be there in the sdk

### ISSUE THREAD

**Issue by rnbokade** [nhost/nhost#2226]
This feature would allow, us one to create customizable web-components for frontend, which take NHOST instance as param and generate sign in sign up components automatically with all the methods that are enabled

**Comment by dbarrosop** [comment]
Could you elaborate? I am unsure what you mean with "The ability to query enabled auth methods"

**Comment by rnbokade** [comment]
Something like nhost.getauthmethods() which returns a list [{type:emailpass, params:{minlength:8}}, {type:googleoauth,params:{link:/oauth/google}....}

**Comment by dbarrosop** [comment]
Ok, I'd suggest starting by handcrafting that object and passing it to the components so instead of relying on `nhost.getauthmethods()` the user of the component would've to define it for their application. This will let you move forward without being blocked by us and will also give us more information on how the object may need to look like and what data may be needed.

If you start working on these components and are planning to opensource, please, share the repo and keep us posted on the progress.

**Comment by tehpsalmist** [comment]
Why not just start simple by returning the strings? You can use an object so it is extensible in the future, but this is a great case of YAGNI.

```js
const methods = nhost.getEnabledAuthMethods()
// ['googleoauth', 'emailpass', 'smspasswordless']

// ...or
// [{ name: 'googleoauth' }]
// now you can add more stuff to the object if it makes sense later (spoilers: it won't)
```

Really the name of the provider is all you need to build stuff with it, because each auth provider is proprietary enough to defy a clean abstraction. If I'm wrong later, no harm done. But if I'm right, then there was no need to wait on delivering this feature. Maybe I'll cook up a PR...

**Comment by tehpsalmist** [comment]
Case in point, if you look at the way the internal graphql api exposes each method, they are treated like individual entities. https://github.com/nhost/nhost/blob/main/dashboard/src/gql/app/settings/signInMethods/getSignInMethods.graphql
