### ISSUE TITLE
Allow Pull Requests to create a unique Preview Environment

### ISSUE THREAD

**Issue by jmarbutt** [nhost/nhost#23]
Many hosting platforms including firebase and heroku have "review apps" or unique deployments when a Pull Request is created. It would be amazing if you could have a way to create a temporary deployment for a pull request.

**Comment by nunopato** [comment]
@jmarbutt Thank you! `preview environments` are in our roadmap. We are now rebuilding our infrastructure so this will have to wait until that is finished.

**Comment by jmarbutt** [comment]
Yeah I figured that is probably pretty complicated to implement but something I have really enjoyed in Firebase and Heroku.

**Comment by alveshelio** [comment]
Hi guys,

Talking about the preview environment and how it could be difficult to pass an environment variable to Vercel or Netlify, I was looking into an article about building an HTTPS-intercepting javascript proxy and though this could be something worth exploring.

Now, my backed knowledge is very limited so what I might be suggesting doesn't make sense at all :)

So what if, instead of passing an environment variable to Vercel or Netlify, instead you have an HTTPS-intercepting proxy on Nhost that whenever you create a PR it would intercept the traffic and route it to the preview environment. I know that whenever we create a PR Vercel generates a URL for this PR, maybe somehow grab this URL and redirect traffic to the preview environment from this URL.

By doing so, you wouldn't need to worry about the different front-end hosting providers.

Does any of it makes any sense?

**Comment by nunopato** [comment]
@alveshelio thank you for your suggestion. We will consider it when building the feature. I didn't know about HTTPS-intercepting proxy until now.

**Comment by guicurcio** [comment]
For anyone looking at this issue, one way to circumvent it ( until we have preview environments) is by creating a new application, connecting it to the same GitHub repository and editing the branch to the one from the PR.
