### ISSUE TITLE
Password reset ticket invalidated before use

### ISSUE THREAD

**Issue by ajluker** [nhost/nhost#2314]
We've noticed an issue with the password reset flow. The link sent to the user is a one time ticket that enables them to login. It looks like this ticket is deleted as soon as there is a GET request to the verify endpoint. We've seen certain Mail Transport Agents perform checks on links embedded in emails, which will result in a GET request to the endpoint, making use of the one time ticket. By the time the user receives their email, the ticket has already expired. 

It looks like this has been encountered in the past for other platforms, in other similar scenarios, such as email clients providing previews of links, so I don't believe the issue is limited to MTA link scanning. Here is an example of a very similar thing being raised for Drupal - https://www.drupal.org/node/2828034

The conclusion made there, which makes sense to me, is that a GET request shouldn't change a resource. So expiring something on a GET isn't respecting the HTTP protocol. Their solution appears to be landing the user on page when they follow the ticket, which has a form that they need to submit, triggering a POST that would then log the user in. Link scanning or previews won't submit the form (or make POST requests) and thus won't expire the ticket.

Is there a way to avoid this problem with Nhost?

**Comment by dbarrosop** [comment]
Thinking about this issue you should be able to fix it yourself very quickly. You can basically change the email [template](https://docs.nhost.io/authentication/email-templates) to make sure the link points to your own application. You have the `link` and `ticket` [variables](https://docs.nhost.io/authentication/email-templates#variables) available so you can implement this the best way for you. For instance, you could change the template to include the link `https://myapp.com/reset-password?redirecTo={link}` instead of the default one (which is just `{link}`. Then in that page you could present the user with a form or just perform the POST automatically with the help of a bit of javascript magic, whatever suits your application. The advantage of this solution is two-fold:

1. You have full control to do this in any way you want.
2. Everything remains on brand as opposed to some generic form coming from hasura-auth's domain, which might be off-putting for the user.

Let me know what you think.

**Comment by ajluker** [comment]
Hi David, thanks for getting back to me.
I had the same idea, which I think will hopefully work for us, although it feels like an issue that should be addressed in Nhost for the benefit of other users.

One issue with your exact suggestion, does the template engine come with anything that enables the correct escaping when building URLs? https://myapp.com/reset-password?redirecTo={link} will end up with unescaped question marks etc in the URL.

**Comment by ajluker** [comment]
I can see in the code it doesn't. If I want well formed URLs I can guess I can try and manually build the URL from the finer grained variables

**Comment by dbarrosop** [comment]
> for the benefit of other users

If there is any idea that doesn't introduce too much complexity or that requires changing the semantics of the link we are open to suggestions :)

> does the template engine come with anything that enables the correct escaping

if there is anything that needs adding we can do so but I think it might be better to do something like https://myapp.com/reset-password?ticket={ticket} instead. Ticket is the only info you need that you don't already have in your application

**Comment by st3phan** [comment]
Reading along here. I looked for the correct POST method to verify the `ticket` but wasn't able to find the correct one 😬  Could you please point me in the right direction?

**Comment by dbarrosop** [comment]
There is no POST method, it's just a GET to BASE_URL/verify?ticket={ticket}

**Comment by st3phan** [comment]
So how should one handle the redirect that is done in the `verifyHandler` [here](https://github.com/nhost/hasura-auth/blob/59e588ae4aa2484aed7e9c5f2748a459552465b2/src/routes/verify/verify.ts#L102).
Because `redirectTo` is required we always redirect from the page where we are doing the GET to the `/verify` endpoint. 

Now I am currently ignoring the redirect by setting `redirect: 'manual'` in the fetch options, but then I never get any feedback. Not if the verification was successful or when we have an expired tickets, since this info is in the query string of the page we redirect to. 

Am I maybe implementing this wrong?

**Comment by dbarrosop** [comment]
> It feels like a verifyEmail method could solve the problem?

Maybe, if someone wants to implement a `POST /verify` that works similar to `GET /verify` but returns data instead of doing the redirect we'd be open to PRs.

**Comment by dbarrosop** [comment]
I did some more research on this and the `POST /verify` solution doesn't work. To do a POST to the `/verify` endpoint you need to use a form but that doesn't open a link and, more importantly, doesn't follow any 302 coming as response. This means that you'd need a bit of javascript to emulate the behaviour (do a fetch using the method POST and try to open the link given in the 302), however, this has two issues:

- If you are using a webmail solution this will fail due to CORS
- If you are using a desktop mail client this will fail as javascript execution will certainly will blocked

So the only real solution is the following:

1. The email redirects to www.app.com/verify (instead of hasura-auth)
2. That website has a single button that:
  1. Performs a POST to the subdomain.auth.region.nhost.run/v1/verify
  2. If the POST fails show the error on screen
  3. If the POST returns a 302 follow it

**Comment by chrtze** [comment]
Thanks @ajluker for opening this issue! We were getting complaints from our customers regularly that they are getting the expired token error whenever they try verifying their mails but we could never reproduce this. In case anyone is interested, we implemented the [proposed solution](https://github.com/nhost/nhost/issues/2314#issuecomment-1758171521) from @dbarrosop in nextjs. You can find the route handler [here](https://github.com/xyflow/pro-platform/blob/main/src/app/(auth)/email-verification/verify/page.tsx) and an example email template [here](https://github.com/xyflow/pro-platform/blob/main/nhost/nhost/emails/en/email-verify/body.html#L280).

**Comment by onehassan** [comment]
We were not able to reproduce this using outlook default settings. But we now have React and Vue examples for the workaround described above thanks to @dbarrosop and @chrtze. We encourage others to test the workaround in this [PR](https://github.com/nhost/nhost/pull/2590) and share their feedback on whether it resolves the issue.

**Comment by dbarrosop** [comment]
For reference, here you can find a blog post about the solution:

https://nhost.io/blog/protect-magic-links-from-email-clients

and some example implementations:

https://github.com/nhost/nhost/pull/2590

**Comment by moklick** [comment]
Is this workaround still necessary with the latest changes to nhost/auth? btw. the blog post url doesn't work.
