### ISSUE TITLE
I can't edit from the dashboard even if I have owner  permission

### ISSUE THREAD

**Issue by RizanPSTU** [nhost/nhost#2330]
<img width="843" alt="Screenshot 2023-10-20 at 11 27 12 AM" src="https://github.com/nhost/nhost/assets/32144390/d5f15dfc-5b05-453f-a925-26b44dcc5b0c">

**Comment by shubhamsinghshubham777** [comment]
The info message explains it i.e. it assumes since you have connected your project with a GitHub repo, you're likely using [Nhost CLI](https://docs.nhost.io/cli) to develop your app locally.

Therefore making schema changes locally will be reflected in your production schema without you having to do anything which makes sense since no one would want to create/modify their tables multiple times (i.e. at least once for every environment flavor) increasing the chances of manual errors/mismatches.

**Comment by dbarrosop** [comment]
that is correct, you can't modify the database schema directly in the cloud if you have a github repository connected as that would cause drift between the cloud and your github repository that would probably lead to issues.
