### ISSUE TITLE
Hasura doesn't work

### ISSUE THREAD

**Issue by igor-adzz** [nhost/nhost#2641]
When trying to disable Hasura's dev mode I lost access to Hasura's UI. The icon is greyed out. Dev mode is not disabled, it is automatically switched to On after the page reloads. I'm using Hasura v2.38.0-ce and Nhost Pro.

![image](https://github.com/nhost/nhost/assets/127742125/58f551d3-f775-4c79-b8d4-bac867723848)

**Comment by dbarrosop** [comment]
Thanks for raising this issue, we will fix ASAP as this is a bug in the dashboard. Looks like, by mistake, when we save that setting we are disabling the console instead of `devMode`. We will try to release a fix today.

In the meantime, you can fix it in the `nhost.toml` (if you have a connected repo), or, if you tell me your subdomain I can fix it for you.

**Comment by dbarrosop** [comment]
Done.

Let's leave the issue open as we still need to fix this in the dashboard.

**Comment by dbm03** [comment]
Was solved in #2647
