### ISSUE TITLE
Nhost (Next) JWT Token expire and apollo/nhostNext js client stops working

### ISSUE THREAD

**Issue by AlexanderMoroz** [nhost/nhost#2681]
**Describe the bug**
Hi everyone. I've decided to open this bug once more because we have still issues related to JWT expiration and session refresh with next/apollo/nhost.

prev bug #2348 

I've recorded a pretty detailed loom about this: 
https://www.loom.com/share/d5f716675c924192b3f3cedc3fa32e0e

Basically, if we get an error in nhost-apollo client  `cannot read property type of undefined` which we get when we got `JWT token expired` error message from hasura, apollo client and nhost native client stops sending any request at all. What is more annoying that there is no error and page refresh doesn't help at all. User have to sign-out at least. The only request which is successful after page load is request to `v1/token`.

We've recently updated to the latest versions of nhost and apollo libs:

```json
"@apollo/client": "3.9.11",
"@nhost/apollo": "^6.2.1",
"@nhost/nextjs": "^2.1.10",
"@nhost/nhost-js": "^3.0.11",
"@nhost/react": "^3.4.1",
"@nhost/react-apollo": "^11.0.1",
```

I'd like to provide any possible help to solve this issue, because it's quite crucial for our application.

Looking forward to your response.
Thanks in advance

**Comment by onehassan** [comment]
Thank you for providing a detailed issue. We will take a look at this as as soon as possible.

**Comment by mmmoli** [comment]
Thanks @onehassan

This is crazy critical for us because it keeps triggering on prod every 10mins and we have no way to fix.

**Comment by dbarrosop** [comment]
We are having troubles replicating and we don't know of any other user having this issue. All the reports we have heard so far from the users affected by the previous issue is that the issue is no longer a problem so we will need help finding a way to replicate. However, before that, would you mind checking your session settings (settings->Authentication->Session)? Which values do you have?

**Comment by AlexanderMoroz** [comment]
@dbarrosop could you give me a hint we're are this settings exactly? Not quite sure I got what you meant

**Comment by dbarrosop** [comment]
> settings->Authentication->Session

**Comment by AlexanderMoroz** [comment]
Hmmm.. this is not available during local development, but this is our settings from production:

<img width="1117" alt="image" src="https://github.com/nhost/nhost/assets/11835202/8f59ef09-d2eb-48db-ba6c-fa3ba3be7110">


But I've continue my debugging and found something interesting regarding this `stale` state of application. At least why apollo is not doing any request. We have a bit weird inconsistent state of our access token

I was mainly looking at this file: 
https://github.com/nhost/nhost/blob/main/integrations/apollo/src/index.ts and how it works on my local machine.

So, problem:

apolloLink calls `await getAuthHeaders()`

```ts
 const httpLink = setContext(async (_, { headers }) => {
    return {
      headers: {
        ...headers,
        ...(await getAuthHeaders())
      }
    }
  }).concat(createHttpLink({ uri }))
```
`getAuthHeaders` under the hood calls `await awaitValidTokenOrNull()` which calls `isTokenValidOrNull` recursively
```ts
const awaitValidTokenOrNull = () => {
    if (isTokenValidOrNull()) {
      return Promise.resolve()
    }

    const waitForValidToken = () => {
      if (isTokenValidOrNull()) {
        return Promise.resolve(true)
      }
      return new Promise((resolve) => {
        setTimeout(() => waitForValidToken().then(resolve), 100)
      })
    }

    return waitForValidToken()
  }
```
but token which have is never null or never valid. Basically because JWT is not valid during bug is present. 
If we take a look at values: 
![image](https://github.com/nhost/nhost/assets/11835202/2c330444-652b-45e4-b45a-d7f48f603e0a)

Our token expires in future (time of screenshoot is 14.15 local).
But if we decode JWT it's in the past 
![image](https://github.com/nhost/nhost/assets/11835202/2a4ff14a-21a5-4511-ac27-dcb21ffd91b2)
<img width="476" alt="image" src="https://github.com/nhost/nhost/assets/11835202/2536b93f-5bf9-4f57-b027-6e69836d7459">

So I def continue debugging this and try to understand where is this inconsistency coming from (I assume this might be because we can use two nhost clients next and vanila (because of monorepo and some parts are need to be reused outside of next js) 

But would be great to hear any feedback from you. Maybe it make sense to at least reset auth state if JWT is in the past or not valid, because otherwise you have infinite loop

**Comment by AlexanderMoroz** [comment]
@dbarrosop @onehassan any updates?

**Comment by dbarrosop** [comment]
No, I think first step will be for you to provide us with the means to reproduce. As mentioned previously, to the best of our knowledge this issue was fixed and it looks like this issue might be related to your setup so we need help reproducing (we also have a monorepo as you can see in our nhost/nhost repo and we don't have this issue)

**Comment by dbarrosop** [comment]
Alternatively, a PR with the fix will be more than welcomed :)

**Comment by AlexanderMoroz** [comment]
Ok, I'll try to update previous repo I sent you to reproduce this error. Or if I understand how exactly I can fix it I'll just create a PR

**Comment by mmmoli** [comment]
Disappointed with the response from @dbarrosop 

Reads like, "not our problem until you can prove that it is".

You're always going to be bombarded with issues that feel isolated like this, with every customer fighting for your attention.

From our pov, our entire stack relies on nhost being solid regardless of where the bug lives.

It's not solid. 

@AlexanderMoroz has done a detailed investigation. We lack the knowledge of nhost internals to go much further and since we haven't received any further direction.

Instead, you propose we do more work to prove to you this is a bug?

Sure, ok. 

Remind me why we should make a PR again? After all, it's our problem, right?

;)

**Comment by dbarrosop** [comment]
> Reads like, "not our problem until you can prove that it is".

I am sorry if it came across that way, it certainly wasn't my intention.

> You're always going to be bombarded with issues that feel isolated like this, with every customer fighting for your attention.

Agreed. That's why we need to prioritize based on:

a. how many users are affected
b. reproducibility (hard to fix an issue if you can't replicate it or don't know the conditions that trigger it)

Unfortunately, we don't know how to reproduce/trigger this issue. The excellent analysis done by @AlexanderMoroz seems to indicate there is something special in this setup so we need help replicating these conditions so we can look into it.

> Instead, you propose we do more work to prove to you this is a bug?

No, nobody is saying you need to prove this is a bug. All I said is we need a way to reproduce it. It is very difficult to fix a problem if we don't understand that conditions that trigger it.

> Remind me why we should make a PR again? After all, it's our problem, right?

Nobody said that. In all my communications all I have said over and over is that we need help reproducing. I personally think that an issue that invalidates the session every 10 minutes is a pretty serious issue and if you are running into it other users may run into it, so it is in our best interest to find a solution. But again, we are running blind here.

**Comment by mmmoli** [comment]
@dbarrosop I do get it. It's a balance and it's on us to give you something more to work with.

Thank you for acknowledging the effort @AlexanderMoroz already put into this. We'll try to find the time to probe further.

**Comment by onehassan** [comment]
It is expected that requests will stop firing when the JWT has expired, because otherwise you'll receive a 401 response.
Could you provide further insights into your setup and the initialization of the Nhost clients?. 
Timing also looks weird to me because the expiration is set to 15mns but you mention that it happens consistently every 10mns!
Any details that would help me reproduce this using a minimal setup would be very helpful.

**Comment by chiemerieokorie** [comment]
Can confirm this issue on my end -- been trying to fix it for weeks.

**Comment by dbarrosop** [comment]
Could you provide more details about your setup and the conditions in which it triggers? Any help/info is welcomed as we are having issues reproducing this issue.

**Comment by AlexanderMoroz** [comment]
Guys, next week I'll have some extra time to sort this out, so hopefully will give more info how to reproduce it.

My gut feelings tell's me this happens when you have few (we have two) separate nhost client instances. 
In our case we have one which we use outside of react-cycle:

<img width="570" alt="image" src="https://github.com/nhost/nhost/assets/11835202/c7f8c6fa-4e1d-4366-a57e-374e09c80315">

and one which is in react created by same function in `NhostApolloProvider` as part of your nhost/react-apollo package

<img width="540" alt="image" src="https://github.com/nhost/nhost/assets/11835202/66bb8974-d894-41c2-9ebf-a5392c8dc33a">

I'll try to give you more info next week.

**Comment by dbarrosop** [comment]
A couple of questions:

1. Do they connect to the same backend? I guess they do but better to double check.
2. Are both clients expected to run on the same domain/browser? Mostly wondering if both clients might be writing/reading the same session

I have a couple of ideas we could try to get more datapoints:

1. Is it possible to consolidate the clients or remove one of them? Even if it's just for testing in development or similar. This would confirm your theory, which I am inclined to agree on as there might be some race condition as both clients interact with the same session, potentially triggering at different times and stepping on each other.
2. If (1) isn't possible maybe setting a VERY HIGH `refreshIntervalTime` (i.e. 2 hours) in one of the clients and see if the problem goes away (or rather, takes 2h to reproduce).
3. We could also try setting `autoSignIn` and `autoRefreshToken` on one of the clients. This might actually make the problem go away if it is an issue with both writing to the same session.

**Comment by AlexanderMoroz** [comment]
hey! 

So, answers to the first questions.
1. Yep, they do connect to the same nhost backend instance
2. Yep, they're running in the same browser/client. 

About ideas:
1. Hard to achieve but I'll try. That's actually was my plan. 

Right now we have a quick fix which is a bit ugly but works perfectly as workaround:

we run this function for each nhost client instance as soon as we create it: 
```ts
import { NhostClient } from '@nhost/nhost-js';
import { wait } from '@htch/utils/ts';
import { jwtDecode } from 'jwt-decode';

export function listenToJWT(nhost: NhostClient) {
  const run: () => Promise<void> = async () => {
    const interpreter = nhost?.auth.client.interpreter;
    if (!interpreter) {
      await wait(1000);
      return run();
    }

    interpreter?.onTransition(async (state, event) => {
      if (['SIGNOUT', 'SIGNED_IN', 'TOKEN_CHANGED'].includes(event.type)) {
        if (!state.context.accessToken.value) return;
        const jwt = jwtDecode(state.context.accessToken.value);
        if (!jwt.exp) return;
        if (jwt.exp * 1000 < Date.now()) {
          console.warn(
            'refreshing session, JWT is incorrect: ',
            new Date(jwt.exp * 1000).toString()
          );

          await nhost.auth.refreshSession();
        }
      }
    });
  };

  run();
}
```

this is definitely not a fix, but it works as a temporary solution

**Comment by dbarrosop** [comment]
@AlexanderMoroz how is this going? Did you manage to find more about this issue?

**Comment by AlexanderMoroz** [comment]
Hello! Unfortunately no. My fix above was kinda enough for us to stop having critical bugs, but didn't manage to dig deeper. 
I'm 90% sure this is due to race conditions between two nhost client instances and you might want to address it but also not sure that a lot of people using your library in such **questionable** way. 

I stopped working on this project and it's not in active development, so if you need any more help you can ask @mmmoli or close this issue for now. 

Thanks in advance.

**Comment by dbarrosop** [comment]
Thanks for the update, let's a wait a bit and see if there is any update or we will close otherwise.

**Comment by dbarrosop** [comment]
We haven't heard more from this so we will be closing, feel free to reopen if it's still a problem and can provide the information requested. Thanks!

**Comment by KDShah71** [comment]
@dbarrosop ; 
For my mobile app the client "@nhost/react" don't work when app is in background so I had to use @nhost/nhost-js ;
I am facing the same issue ;

 How to Reproduce the Issue

To reproduce the problem where the @nhost/nhost-js client fails to refresh the access token automatically, follow these steps:

Client Initialization: Use the provided code to initialize the @nhost/nhost-js client.
 
packages

```
  "@apollo/client": "^3.11.8",
    "@nhost/react": "^3.5.6",
    "@nhost/react-apollo": "^12.0.6",
```

```
import { NhostClient } from "@nhost/nhost-js";
import AsyncStorage from "@react-native-async-storage/async-storage";
import env from "../config/env";

// Initialize the Nhost client
const nhost = new NhostClient({
  authUrl: `https://${env.NHOST.AUTH_URL}/v1`,
  graphqlUrl: `https://${env.NHOST.SUBDOMAIN}.graphql.${env.NHOST.REGION}.nhost.run/v1`,
  functionsUrl: `https://${env.NHOST.SUBDOMAIN}.functions.${env.NHOST.REGION}.nhost.run/v1`,
  storageUrl: `https://${env.NHOST.SUBDOMAIN}.storage.${env.NHOST.REGION}.nhost.run/v1`,
  clientStorageType: 'react-native',
  clientStorage: AsyncStorage,
  autoSignIn: true,
  autoRefreshToken: true,
  ...(__DEV__ && {
    debug: true,
  }),
});

export { nhost };
```

Authentication Settings: Manually set the access token expiration time to a short duration (e.g., 120 seconds) in your Nhost project's authentication settings.

Monitoring Logic: Use the following useEffect hook in a React Native component to monitor the client's authentication state and access token expiration. This logs the state every 30 seconds.
JavaScript

```
    useEffect(() => {
      const interval = setInterval(async () => {
        console.log("DEBUG", {
          isAuthenticated: await nhost.auth.isAuthenticatedAsync(),
          accessTokenExpiresIn: nhost.auth.getSession()?.accessTokenExpiresIn
        });
      }, 30000); // 30 seconds

      return () => clearInterval(interval);
    }, [nhost]);
```

Observe the Logs: After the user signs in, observe the logs. The isAuthenticated status will correctly show true while the accessTokenExpiresIn value is positive. However, once the accessTokenExpiresIn value drops below zero (i.e., after the token has expired), the isAuthenticated status will incorrectly switch to false, and the client will not attempt to refresh the token.

Log Output Analysis

The provided log output clearly demonstrates the failure:

    LOG DEBUG {"accessTokenExpiresIn": 89.911, "isAuthenticated": true}: Token is valid.

    LOG DEBUG {"accessTokenExpiresIn": 59.9, "isAuthenticated": true}: Token is still valid.

    LOG DEBUG {"accessTokenExpiresIn": 29.886, "isAuthenticated": false}:

The access token has expired (as a 30-second interval has passed), and the isAuthenticated status has incorrectly become false instead of triggering an automatic token refresh. This is the reproducible bug.
