### ISSUE TITLE
Change metadata for user in dashboard

### ISSUE THREAD

**Issue by kelkes** [nhost/nhost#2684]
**Is your feature request related to a problem? Please describe.**
It's not. It's more convenience (don't have to switch to the Hasura console to finish creating a user)

**Describe the solution you'd like**
It would be handy if we were able to edit the user's metadata field through the dashboard (auth).

**Describe alternatives you've considered**
Keep using Hasura console.

**Additional context**
My client uses the nhost dashboard to create users, but is not techy enough to use the Hasura Console to add the required metadata.

**Comment by dbarrosop** [comment]
Hi, this makes sense, however, I am a bit "concerned" about this statement:

> but is not techy enough

I say a bit "concerned" (very big quotes :P) because the field is of jsonb, which means the easiest/most feasible thing to do here is to add a freeform input text form and expect the user to enter valid json. We can add validation and help with the formatting and whatnot but I think it'd be hard to add something here that can support any valid jsonb object that isn't just an input form. If you have alternative suggestions feel free to propose.

**Comment by kelkes** [comment]
I get that. I would provide my clients with a valid jsonb where they only need to change some values (in my current case, it's about multi-tenancy and giving a user access to a specific set of data).

So basic validation (aka is it a valid jsonb) and a textarea would be sufficient. Formatting a plus.
