### ISSUE TITLE
local.functions.nhost.run  --> local.functions.local.nhost.run transition incomplete?

### ISSUE THREAD

**Issue by dionjwa** [nhost/nhost#2865]
**Describe the bug**

At some point, the local development URLs went from 

`https://local.functions.nhost.run`

to 

`https://local.functions.local.nhost.run`

So this broke my application, and in trying to fix it, there are places internally where the former is still used, e.g. the docker-compose.yaml generated by `nhost`

The `@nhost/nhost-js` module is the latest version, and it returns `https://local.functions.nhost.run` for the functions URL, not the latter. 

So which URL to use? Is the goal to be consistent? Or are there places where one is used and not the other?

The app especially breaks when there are communication between services and those URLs need to be known ahead of time.

**To Reproduce**

Start the nhost stack and you see:

```sh
Nhost development environment started.
URLs:
- Postgres:         postgres://postgres:postgres@localhost:5432/local
- Hasura:           https://local.hasura.local.nhost.run
- GraphQL:          https://local.graphql.local.nhost.run
- Auth:             https://local.auth.local.nhost.run
- Storage:          https://local.storage.local.nhost.run
- Functions:        https://local.functions.local.nhost.run
- Dashboard:        https://local.dashboard.local.nhost.run
- Mailhog:          https://local.mailhog.local.nhost.run
```

Then look in the docker-compose. The urls will be the older form

Get the `nhost.functions.url` from the `NhostClient` from the module `@nhost/react@3.1.8`. It returns the former not the newer latter. 

**Expected behavior**

All URLs are in the newer form.

**Desktop (please complete the following information):**
 - OS:macos
 - Browser Chrome
 - Version: 128.0

**Smartphone (please complete the following information):**

**Additional context**

```sh
❯ nhost --version
nhost version v1.24.0
```

**Comment by dbarrosop** [comment]
Hello,
thanks for raising the issue.

> At some point, the local development URLs went from

Here you can see it in the release notes:

https://github.com/nhost/cli/releases/tag/v1.22.1

We also announced it on discord and it's in the dashboard under "Latest announcements".

I understand it is virtually impossible to read the release notes of every software you update but I'd advise reviewing them if something unexpected happens. We usually add lots of warning emojis to make them stand out when there is something that could have some impact.

> So this broke my application

This is unexpected as old URLs should still work. Could you detail how this broke your application?

> there are places internally where the former is still used, e.g. the docker-compose.yaml generated by nhost

I am looking at the docker-compose file and all I see is that both the old and the new URL should work:

- this is in the functions container:

```yaml
        labels:
            ...
            traefik.http.routers.functions.rule: (HostRegexp(`^.+\.functions\.local\.nhost\.run$`) || Host(`local.functions.nhost.run`))&& PathPrefix(`/v1`)
            ...
```

which should cause it to respond to both urls.

- this is in every container:

```yaml
        extra_hosts:
            ...
            - local.functions.local.nhost.run:host-gateway
            ...
            - local.functions.nhost.run:host-gateway
            ...
```

So every container should know how to reach both urls.

> The @nhost/nhost-js module is the latest version, and it returns https://local.functions.nhost.run for the functions URL, not the latter.

This is explained in the [docs](https://docs.nhost.io/guides/cli/subdomain)

> So which URL to use? Is the goal to be consistent? Or are there places where one is used and not the other?

The goal is to migrate but nothing should break and both are currently supported while people transition.

> The app especially breaks when there are communication between services and those URLs need to be known ahead of time.

As mentioned before, this is unexpected so if you can provide more information and steps to reproduce that would be greatly appreciated as based on our tests things should work.

Thanks again for raising the issue. Please, let us know how to reproduce this because the goal was to make things backwards compatible for the time being. If it's not too much of a hassle a repo reproducing the issue would be greatly appreciated (or even just a PR making the issue obvious in the "test project" we have in the cli repo: https://github.com/nhost/cli/tree/main/examples/myproject

**Comment by caudurodev** [comment]
Has this been updated for local dev javascript libraries such as '@nhost/react-apollo' and "@nhost/nextjs" ? It appears they still call the old urls. I fixe by adding both old and new urls to hosts file. But definitely a bit confusing to debug.

**Comment by dbarrosop** [comment]
> Has this been updated for local dev javascript libraries

There is nothing to update, please, read my previous message and, in particular, the linked release noted.

> I fixe by adding both old and new urls to hosts file

Which hosts file? You shouldn't need to edit anything.

> But definitely a bit confusing to debug

What was broken? Which error were you getting? How can we reproduce?

**Comment by dionjwa** [comment]
Got it, thanks. You can close this issue. Yes, I did not read the release notes, since I assumed this was a bug since it was confusing. Appreciate the detailed response 👍🏻

**Comment by dbarrosop** [comment]
Ok, cool, if you have more questions don't hesitate to let us know.
