### ISSUE TITLE
Make the internet ingress postgres connection pool configurable (or increase the default pool size?) 

### ISSUE THREAD

**Issue by juicygoose** [nhost/nhost#2884]
**Is your feature request related to a problem? Please describe.**
We are using an external administration tool to handle admin processes in our postgres database (Forest Admin) and they are using AWS lambdas to connect, making their connections be quite spiky. Although they can limit the number of connections on their side, I feel like being able to finetune the number of connections from each side would be the optimal solution as 10 connections is too small of a pool for admin purposes (I am only guessing by my limited experience).

**Describe the solution you'd like**
I would like to be able to either configure the connection pool size or at least have 2x more connections that what is allowed today (10).

**Describe alternatives you've considered**
I have considered personally limiting with another layer of pgbouncer but it just creates a bottleneck earlier in the transaction. I am also in active discussion with forest admin to limit the concurrent number of calls they perform to the database. 

**Additional context**
![image](https://github.com/user-attachments/assets/8b636d21-b325-455b-8155-5b604087333f)
![image](https://github.com/user-attachments/assets/b71a3cb8-8086-4789-99f9-e62c33ba18d4)
In Yellow is the number of pending connections to postgres
Related help post in nhost discord https://discord.com/channels/552499021260914688/1286234912076075049

Thanks a ton for the help ! 🌈

**Comment by dbarrosop** [comment]
Let us discuss this internally and get back to you. In the meantime, a few clarifications on your comment:

> 10 connections is too small of a pool for admin purposes

Unless you are performing VERY LONG SQL queries that take minutes to complete or have hundreds of conncurrent slow clients 10 should be more than enough for most use cases. For reference, hasura-auth can serve thousands of requests per second with only 4 connections and hasura's default pool size is 50. As another datapoint, this is the first report we see this is a problem since pgbouncer was introduced 2 years ago. Not trying to argue against the request, just clarifying your comment for other readers.

> I have considered personally limiting with another layer of pgbouncer but it just creates a bottleneck earlier in the transaction

This isn't going to help.

Finally, keep in mind a couple of things:

- to avoid problems you may need to change postgres' maxconnections
- spiky connections may put a strain on your database requiring you to add extra resources to it or suffer a performance hit. Specially if these spikes are occurring during business hours when you are serving traffic to your customers

**Comment by dbarrosop** [comment]
We just increased the pool to 20 so I will be closing this for now. Let's see if that helps you. Otherwise feel free to reopen the issue.
