### ISSUE TITLE
Possibility to integrate with existing authentication provider

### ISSUE THREAD

**Issue by samuelchanx** [nhost/nhost#329]
Hello nHost team, thanks for the great product!

But may I know if it's possible to reuse any existing authentication provider for the JWT authentication in hasura? For example, can I also support Firebase for authentication in addition to nHost auth?

https://hasura.io/docs/latest/graphql/core/auth/authentication/jwt/#introduction

Currently, the system doesn't allow me to set the `HASURA_GRAPHQL_JWT_SECRET` ENV, which is how hasura adds a JWT authentication.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/6096534/161408666-0aae3983-5a55-44d6-ae3d-b567330af2bc.png">

**Comment by penumatv** [comment]
As far as I knew, NHost is not exposing this environment variable (`HASURA_GRAPHQL_JWT_SECRET`) if NHost exposes this variable, that will be a huge win-win for the existing projects also opens the doors for integrating NHost with some of the Authentication providers like Super Tokens and Clerk

**Comment by jmarbutt** [comment]
I think this would be awesome to allow support for Clerk.

**Comment by jmarbutt** [comment]
With Clerk, I know it is setting the `HASURA_GRAPHQL_JWT_SECRET` like this 

```json
{"jwk_url":"https://<YOUR_FRONTEND_API>/.well-known/jwks.json"}
```

I think the hard part for something like clerk, is we would want to keep using clerk because of some of the features it supports around their session management. Would it make sense to put those as feature requests?

**Comment by penumatv** [comment]
Hi @elitan , What exactly I need is to edit the value inside the session variable `NHOST_JWT_SECRET `so that it will allow the developers to decouple the current offering of NHost (i.e. Auth + Hasura & Database) and bring their own Auth (i.e. Clerk or Super Tokens etc) and use the Hasura & Database part from NHost

Currently, NHost auth is connected to the Hasura via `type, key` combination. However, there is one more way to bring the Auth is via `jwk_url `and this can also be easily set up by editing the `--jwt-secret` inside the docker setup. So if you allow setting this up either via Dashboard or manually editing that can offer a smooth transition to the developers who would prefer choose the decoupled architecture. 

Any Thoughts?

**Comment by elitan** [comment]
Make sense. Relevant issue here: https://github.com/nhost/hasura-auth/issues/123

**Comment by penumatv** [comment]
Hi @elitan would you consider this option any time soon? i.e. exposing the `HASURA_GRAPHQL_JWT_SECRET` via NHost dashboard? so that I can bring the jwk (looks like below) and have Clerk integrated with NHost
I am also okay if you manually edit the docker file and set this on 
`--jwt-secret`

`{"jwk_url":"https://<YOUR_FRONTEND_API>/.well-known/jwks.json"}`

Any thoughts? this kind of feasibility will open the doors for developers to bring their own Auth

**Comment by bcdrme** [comment]
Hello @elitan ! I have the exact same issue. I was looking for a way to integrate Outseta with Nhost, and to my surprise `HASURA_GRAPHQL_JWT_SECRET ` isn't available for modification.

**Comment by elitan** [comment]
> Hello @elitan ! I have the exact same issue. I was looking for a way to integrate Outseta with Nhost, and to my surprise `HASURA_GRAPHQL_JWT_SECRET ` isn't available for modification.

I think we should allow editing the JWT secret to allow integration with other providers. I'll add that to our near-term road map.

Our goal with Nhost is not to only work in isolation, but to work with other services too that might work better for your use case.

In the meantime, if you need us to change the JWT secret, we can do it manually. Please reach out to support@nhost.io and we'll make it happen.

**Comment by nunopato** [comment]
We will be working on this pretty soon so that you are able to set `NHOST_JWT_SECRET` with a key from elsewhere.

**Comment by guicurcio** [comment]
Hello [bcdrme](https://github.com/bcdrme), [venkata-penumatsa](https://github.com/venkata-penumatsa) & others. This feature is ready to be tested, please contact me at guido@nhost.io so we can do a step-by-step guided integration and see if we need to make something clearer or fix any bugs :+1:

**Comment by elitan** [comment]
It's now possible to change the JWT Secret in the Nhost Dashboard:

![image](https://user-images.githubusercontent.com/331818/177949453-3d05c009-bf13-4af3-bde3-c9fb68a005a2.png)

**Comment by venkata-penumatsa** [comment]
Hi @guicurcio @elitan I just tested this feature. I put my own jwk url inside the NHOST JWT SECRET and tried sending a GraphQL query from my Next JS app, but I got the following error.

 `Could not verify JWT: JWSError JWSInvalidSignature`

This is how my setup look like. I would like to pass the JWT from [Clerk](https://clerk.dev/)

<img width="325" alt="image" src="https://user-images.githubusercontent.com/41994139/179228561-e0a50701-3b52-44e4-a961-72eeda0b443b.png">

**Comment by bcdrme** [comment]
Hello @venkata-penumatsa ! I'm using Clerk as well.
Jwks are apparently unsupported for now, setting a jwks as en environnement variable will break nhost (happened to me this week).

What you can do however is setting a JWT using the following format
`{"type": "HS256", "key": "<MY_CLERK_JWT>"}`

Replace the key with what you can find in Clerk 
`Dashboard > API Keys > JWT Verification Key`

You don't need to use their jwk as explained here : https://clerk.dev/docs/request-authentication/validate-session-tokens#instructions

**Comment by venkata-penumatsa** [comment]
@bcdrme Hi Thanks for the details. I will work on this and get back.

**Comment by venkata-penumatsa** [comment]
@bcdrme Hi Benoit, Thank you for all of the information. I just tried to set the HS256 value. I let NHost generate the key, then copied it and pasted it into the Clerk's signing key field, and both are now integrated. There is some confusion in setting up the type and key pattern instead of the jwk url, which is very simple. Also, do we need to keep anything else when we combine these two tools in this manner? Is this ready for production? Is your application currently in production?

**Comment by venkata-penumatsa** [comment]
@bcdrme Thank you for all of your information and assistance. Between @elitan confirmed that they will add the feature to accept jwk url as well. The date has not yet been confirmed.

**Comment by nunopato** [comment]
hi everyone, I just deployed a small fix to allow for the use of Clerk and `jwk_url`.

As of now, `NHOST_JWT_SECRET` supports either a (`type`, `key`) pair or a single `jwk_url`. One of them needs to be present.

- if the pair (`type`, `key`) is used, hasura auth is started as usual and shares that pair with hasura.
- if `jwk_url` is used, we assume you are using an external auth provider like Clerk.

To use Clerk with Nhost, update the `NHOST_JWT_SECRET` variable of your app with the right url (e.g., `{"jwk_url":"https://clerk.helpful.gull-71.lcl.dev/.well-known/jwks.json"}`). 

@venkata-penumatsa I did some testing on my side and things seem to be working, please let me know if that works for you.

**Comment by venkata-penumatsa** [comment]
@nunopato Hello, Nuno. I'll test it and report back. Thank you for implementing this new feature so quickly.

**Comment by venkata-penumatsa** [comment]
@nunopato Hi Nuno,I just integrated the Clerk with NHost by using the jwk_url. I just pasted the Clerk's front end jwk_url in NHost environment variable (i.e. NHOST_JWT_SECRET) and they both are integrated now. I am able to pass the JWT in the query/mutation header from my Next JS application and Hasura is responsing back. Already executed few queries and mutations. Thank you for adding this feature I also request your team to have this added to your official documentation so that it will help the developers to know.

**Comment by nunopato** [comment]
@venkata-penumatsa no worries, glad it is working for you now. We will be adding this to the documentation soon, thank you!

**Comment by mmmmillar** [comment]
> hi everyone, I just deployed a small fix to allow for the use of Clerk and `jwk_url`.
> 
> As of now, `NHOST_JWT_SECRET` supports either a (`type`, `key`) pair or a single `jwk_url`. One of them needs to be present.
> 
> * if the pair (`type`, `key`) is used, hasura auth is started as usual and shares that pair with hasura.
> * if `jwk_url` is used, we assume you are using an external auth provider like Clerk.
> 
> To use Clerk with Nhost, update the `NHOST_JWT_SECRET` variable of your app with the right url (e.g., `{"jwk_url":"https://clerk.helpful.gull-71.lcl.dev/.well-known/jwks.json"}`).
> 
> @venkata-penumatsa I did some testing on my side and things seem to be working, please let me know if that works for you.

Hi @nunopato, will this work the same in Hasura Auth?

**Comment by venkata-penumatsa** [comment]
@mmmmillar you want to connect Hasura Auth with `jwk_url` instead of `type, key` ?

**Comment by mmmmillar** [comment]
@venkata-penumatsa yeah that's what I'd like to do

**Comment by venkata-penumatsa** [comment]
@mmmmillar Also, how are you currently utilising Hasura Auth? Do you connect to Hasura using this as a stand-alone package? (not NHost)

**Comment by mmmmillar** [comment]
@venkata-penumatsa yep using it stand-alone

**Comment by venkata-penumatsa** [comment]
@mmmmillar ok. I believe that this modification must be made while considering the current architecture and how the Hasura auth processes the JWT. I'll let the experts weigh in on this. @elitan @nunopato

**Comment by MichalNemec** [comment]
on latest 0.21.2 with jwk_url it doesnt work.
```
/app/dist/utils/jwt/get-claims.js:9
    throw new Error(`Invalid JWT type: ${env_1.ENV.HASURA_GRAPHQL_JWT_SECRET.type}`);
    ^

Error: Invalid JWT type: undefined
```

**Comment by xmlking** [comment]
I tried to Edit JWT Secret, but got error 
```json
{
  "key": "mykey",
  "claims_map": {
        "x-hasura-default-role": "anonymous"
  },
  "type": "HS256"
}
```
Error: variable value contains object with key "x-hasura-default-role", which is not a legal GraphQL name
