### ISSUE TITLE
Inconsistent behaviour in the Authentication workflow due to background /auth/token API calls

### ISSUE THREAD

**Issue by dikshatekriwal** [nhost/nhost#420]
The Authentication workflow of Nhost SDK is not found stable due to background API calls which stores refresh token and token expiry time in localstorage.
Once logged-in using nhost.auth.signIn function, the token gets expired in few minutes and the self called token api does not help to get the new token.
Also, when trying to login again, the SDK shows this info in console {message: 'User is already signed in', status: 100} and the login function never gets called.
Only after clearing localstorage manually and refreshing the page, it allows to call the login function.
All other function (signup) stops working and throws the same info in console if login is failed.

I've added a screen recording of the whole scenario explained above which will help to understand it better.
https://www.awesomescreenshot.com/video/8364543?key=6d34d3f6ae94d9442a67bbda9364ee7c

**Comment by plmercereau** [comment]
Hello Diksha,
Thanks for your message.

The first part or our issue (token refresh) is most likely related to [this issue](https://github.com/nhost/nhost/issues/405).

I watched your screen recording, which action your 'logout' button is calling? Is it calling `nhost.auth.signOut()`?
The login status is not determined by the presence or absence of the refresh token in localstorage, but is held in memory. The refresh token is persisted so it can be reused when opening a new page.

**Comment by dikshatekriwal** [comment]
Hi @plmercereau ,

Yes the 'logout' button is using `nhost.auth.signOut()`.
Are you stating that we should use the refreshToken (stored by /token API called in the background by Nhost SDK) to get the new access token every 2 minute around?
The /token API is using the new refreshToken and fetching the access token with other data but we are not able to access that response as we are not handling the call.

**Comment by plmercereau** [comment]
When setting the `autoRefreshToken` option of the NhostClient to `true`, which is its default value, the client is supposed to refresh the token automatically and keep an up-to-date access token (JWT) in memory.
In general terms, you shouldn't do any direct API call when using the SDK.

The access token is available through `nhost.auth.getAccessToken()`, or you can also listen to its changes through 
```js
nhost.auth.onTokenChanged((session) => {
  console.log(session?.accessToken)
})
```
I cannot reproduce your bug, if you could give more information about your setup, or even better the code or your project, that would help.

Side note: the access token (the JWT) should __never__ be persisted in local storage for security reasons. When loading the page, the Nhost client is checking if there is a refresh token in the local storage and gets a new JWT with it on startup.

**Comment by dikshatekriwal** [comment]
Now I'm able to understand the workflow how Nhost is treating and handling tokens.
One more question I have here is using nhost.auth.signOut() on logout do clear the localstorage but accessToken still exist in memory when tried nhost.auth.getAccessToken() to get the token.
Is this correct?

**Comment by plmercereau** [comment]
After running `signOut()` the access token is destroyed, so it shouldn't be available anymore through `getAccessToken()`.
I found a bug thanks to your attention, it will be corrected in this PR https://github.com/nhost/nhost/pull/440
Thanks!

**Comment by dikshatekriwal** [comment]
Hi @plmercereau could you help me understand/integrate social provider (Google / Facebook) login workflow?
I've integrated the v1 feature in my portal however in v2 the redirection has changed to /#refreshToken instead of ?refreshToken=XXX.
Is this handled by SDK? if yes then how to redirect to dashboard once it is successfully logged-In using Google?

**Comment by plmercereau** [comment]
Hello Diksha,
Yes, the refresh token is sent as part of the hash (`#`) instead of the search params (`?`), mainly for security as hashes are not transferred back to the server.
When creating the NhostClient, there is an option named `autoSignIn` which defaults to `true`. It looks for the refresh token in the url, and if the `refreshToken` is present in the hash, il will try to authenticate with it.
As a result, if a valid refresh token is in the hash, the user will be automatically signed in.

About how to capture the authentication state:
- documentation [when using React](https://docs.nhost.io/reference/react/hooks#useauthenticationstatus)
- documentation [when using Vanilla](https://docs.nhost.io/reference/sdk/authentication#nhostauthonauthstatechangedevent-session)

**Comment by dikshatekriwal** [comment]
@plmercereau  The /token API is getting called using refresh token from the URL however the refresh token never gets authenticated and the 'isAuthenticated' value is always false when trying to login with social provider (Google/Facebook). 
Direct login works as expected.
I see that you have pushed the fix for SignOut bug. Is it in a new version? I pulled the latest of @nhost/react and @nhost/nhost and still the issue of signOut remains as is for me. Am I missing something?

**Comment by dikshatekriwal** [comment]
@plmercereau Did you see my comment above? Any clarity on that?

**Comment by MelodicCrypter** [comment]
I'm still not getting the flow. I'm also experiencing this one: "User is already signed in". When using the` .signOut()` it doesn't destroy the tokens that were saved in the local storage. What is the proper flow if you want to really logout a user?

By the way, I'm handling my own localstorage variables like isLoggedIn because of this issue. Coz last time I used `.getAuthenticationStatus()` but cannot seem to implement properly when using Svelte. That's why I decided to create my own check locally. But the `.signOut()` is not "working" as well.
