### ISSUE TITLE
Passwordless SMS OTP Auth is broken

### ISSUE THREAD

**Issue by oristian** [nhost/nhost#505]
This is a blocking error for me, so I'll try to add more information than I shared in Discord.  It looks like the API has changed from autoLogin to autoSignIn, and the previous clientStorage* parameters have been deprecated.  Is there something we need to do within our React Native code to flush the refreshToken before switching the backendUrl from local development to the hosted "production" endpoint?  This could be the source of these problems if there is some persistence of an invalid token

PRODUCTION:
on nhost-js 1.1.4 through 1.1.6 I'm experiencing a strange bug after deploying to production.  On the first attempted SMS OTP signin I receive an invalid refresh token error and on subsequent attempted signins I receive an error saying "This endpoint is disabled" -  I'm assuming the config.yaml which I committed to the nhost directory contains the necessary Twilio config to create the necessary AUTH_* environment variables to support Passwordless SMS OTP - am I correct in this assumption?

DEVELOPMENT:
Locally, when running nhost -d, I see the auth/sms/passwordless/otp function get called, but I get a ReferenceError "Can't find variable: localStorage"  I see there were tons of updates related to hasura-auth and environment variables, so I'm gleaning that something may have introduced a regression in the SMS login functionality.  

`  const nhost = new NhostClient({
    backendUrl: 'http://localhost:1337',
    // autoSignIn: false,
    // clientStorage: AsyncStorage,
    // clientStorageType: 'react-native',
  });`

**Comment by plmercereau** [comment]
Hello Mike,
There's quite a few points in the above message:
1. the local configuration (`config.yaml` file) is not synced with the cloud configuration.
2. SMS authentication is not activated in the cloud, but we are currently working hard to make it available by the end of the month.
3. `autoLogin` has been renamed to `autoSignIn` to be consistent with our naming conventions (we were using 'sign in' everywhere except for this option). Although deprecated, it is an alias for `autoSignIn`.
4. the weird invalid refresh token has been fixed in today's release
5. `clientStorage` and `clientStorageType` were incorrectly deprecated. It has also been fixed in today's release. You need to configure it like in [this repo](https://github.com/plmercereau/nhost-js-expo-basic/blob/e3efafa9d76067aa50fb7ad60559c72883827939/App.tsx#L10)

@guicurcio or myself will keep you posted on when it will be possible to configure Twilio in the cloud, thanks in advance for your patience!

**Comment by oristian** [comment]
Thanks for your comment.  I see all your commits and I'm impressed by your velocity right now.  I find it hard to believe that functionality that has been in the documentation for 6 months and in discussions for a year has not made it to production yet.  It was even working last Wednesday!  Yesterday I attempted to put those AUTH_ env variables into production myself, but could not because they are reserved.  I'm confused as to how the local nhost dev is not the same "stack" as what is deployed.  I have been a champion of Nhost for over 15 months.  As of last night my stakeholders on our weekly call have strongly admonished me to pull away from this project and develop our own Hasura-based solution with our codebase.  We are 18 months into our build (left Amplify for Nhost in Feb '21)  trying to go live.  I will follow up with Nuno and Johan under separate cover.  Thanks again for all your hard work for us customers.  I'm still a huge champion of your product but I have lost all my personal credibility with this migration to V2.  It pains me to write this.  I will surely use Nhost in the future on other projects, but it is simply not ready, as you've stated transparently here, which I thank you for immensely.  I just wish I had known sooner.  Cheers.

**Comment by plmercereau** [comment]
Hey Mike, thanks for your kind and honest words. We'll reach out to you soon so we can find a workaround for your app while waiting for the UI to be ready
