### ISSUE TITLE
Apollo subscriptions do not exist

### ISSUE THREAD

**Issue by dyyce** [nhost/nhost#51]
Hey,

not sure if this is the right place, but I couldn't find a support platform.

I am using Nuxt and followed the guide. Also used the same configurations from the nuxt example.
The auth is working fine, but I can't query anything.

I have only 2 tables
- user
- notes

notes is a basic table with
- id
- text
- user_id
- created_at
- updated_at

When I test the queries from within hasura, everything works fine. But I can't query anything from within my application.

I always get this error

```
Error no subscriptions exist
apollo-module.js?0d2d:84 Error GraphQL error: field "notes" not found in type: 'query_root'
apollo-module.js?0d2d:84 Error GraphQL error: field "notes" not found in type: 'query_root'
```

**Comment by elitan** [comment]
99.9% of the time you get errors like "[..] GrahQL error: <> not found in type [..]" it's because there is a permission issue.

Go to the Hasura console and check permissions for the `notes` table and make sure the role `user` has the right permissions.

More info: https://docs.nhost.io/hasura/permissions

**Comment by dyyce** [comment]
Hey Johan,
thanks for your reply. It makes sense. I removed the `nhostAuth` from my component and the subscription started to work.
I will dig deeper into the permission section of the docs :)

Cheers

**Comment by elitan** [comment]
🎉  Perfect
