### ISSUE TITLE
Add support for camelCase in users table

### ISSUE THREAD

**Issue by noverby** [nhost/nhost#52]
Currently, all user fields are snake_case.
According to https://docs.nhost.io/auth/custom-user-columns, these fields should not be deleted.
But using snake_case does fit well into the standard JavaScript convention to use camelCase.

Therefore, it would be neat if nhost supported camelCase.

**Comment by joshua1** [comment]
you can alias your fields (columns) with camelCase properties, and this will be picked up and used in your graphQl queries,mutations,subscriptions

**Comment by noverby** [comment]
I know that, but I'm using auto-generated GraphQL bindings (GQty), and therefore it will just be cleaner, if you can avoid having to do the renaming manually.

**Comment by joshua1** [comment]
I use GenQL. you can follow this issue: https://github.com/hasura/graphql-engine/issues/3320.

**Comment by joshua1** [comment]
@noverby  hasura-camelize will do the job. run it before generating types each time

**Comment by elitan** [comment]
This is now implemented. All tables in `auth` and `storage` schemas are using camelCase.

Reference: https://github.com/nhost/hasura-auth/blob/main/src/metadata.ts#L211-L235

**Comment by dohomi** [comment]
@elitan I just found out about this feature of Hasura. What happens if I would like to change my naming convention to `graphql_default` instead of `hasura_default`? What will happen to the existing tables and columns? Is that something I can change later on or does it need to be defined in the beginning of a project?
