### ISSUE TITLE
Cannot add relationships to the users table

### ISSUE THREAD

**Issue by quentin-decre** [nhost/nhost#666]
I cannot add relationships to the user table :
```
"error": {
      "exec_status": "FatalError",
      "hint": null,
      "message": "must be owner of relation users",
      "status_code": "42501",
      "description": null
    },
```
https://discord.com/channels/552499021260914688/981585092482859068/981585739353575464

Demonstration in video : https://www.loom.com/share/2efff38b077f4113a27b00ce6f7338b5

We started to discuss this issue with Johan and Nuno on discord : https://discord.com/channels/552499021260914688/981585092482859068

**Comment by elitan** [comment]
I think this issue occurs because there is currently a mismatch for permissions between local and cloud.

Using the Nhost CLI, the developer has full access to the `auth` and `storage` schemas.

But in Nhost Cloud, we've limited the permissions for those two schemas to avoid developers messing up those schemas and breaking the authentication and storage services.

This means that database migrations that worked fine locally, are not being applied correctly on Nhost Cloud.

I think the solution to this is what we're currently working on:

1. Give each Nhost app its own Postgres instance (right now we use shared AWS RDS databases).
2. Give full root permissions to the Postgres instance.
3. Build a database UI in the Nhost dashboard in a way that it's hard to mess with the `auth` and `storage` schemas to avoid breaking services.
4. (Somewhat relevant. Under research currently): Let Hasura Auth and Hasura Storage interact directly with Postgres (instead of via GraphQL) to avoid those services being opinionated on the GraphQL and Hasura lawyer (GraphQL root fields etc).

Until the first two points above are released, this issue will persist.

**Comment by elitan** [comment]
In Discord you mention you tried to add the following:

```
CREATE OR REPLACE FUNCTION create_user_group() RETURNS TRIGGER AS $$
    BEGIN
      INSERT INTO public.users_groups(user_id,group_id) VALUES(NEW.id, gen_random_uuid());
      RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER create_user_group_trigger
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION create_user_group();
```

I suspect it's a Postgres permission issue to create a trigger on `auth.users`. It that correct?

**Comment by elitan** [comment]
This should be fixed with the permission work on Postgres that we've done recently.
