### ISSUE TITLE
Misunderstanding tutorial instructions

### ISSUE THREAD

**Issue by dnk8n** [nhost/nhost#673]
It might be me, but perhaps this feedback could be useful to allow less frontend savvy users to get started with your product.

The [changes I made](https://github.com/dnk8n/tech-talk/commit/86336b7f5c6c1e5356ccdd8746c18168f239b21c) according to your [tutorial](https://docs.nhost.io/platform/quickstarts/nextjs) don't result in a running application.

Where have I gone wrong? Perhaps you could put some emphasis on that section, unless I am just plain not following instructions

- The initial signup page renders
- I recieve the email when signing up a new user
- Upon verifying email I get an error as shown in screenshot

![Screenshot from 2022-06-04 11-43-41](https://user-images.githubusercontent.com/3307753/171994033-2d5e22dc-b07b-4724-b979-658404210105.png)
.

**Comment by elitan** [comment]
1. You've removed the `UserProvier` from `_app.js`. It should not be removed.

Your code: https://github.com/dnk8n/tech-talk/blob/main/quickstart-nextjs/pages/_app.js
Template code: https://github.com/nhost/quickstart-nextjs/blob/main/pages/_app.js#L7

2. Once you put it back you'll see "Something went wrong. Try to refresh the page." which is because you have not yet set the correct permissions for users to read their own data. That kind of makes sense because you do that in the [next part](https://docs.nhost.io/platform/quickstarts/nextjs#update-user-data) of the quickstart guide.

Please let me know if this fixed your issue.

**Comment by elitan** [comment]
I think we can be clearer in our quickstart guide about what should be included in `_app.js`. We don't need to save space with `{/* ... */}` in the code block.

![CleanShot 2022-06-04 at 16 54 14@2x](https://user-images.githubusercontent.com/331818/172009058-a7c575fd-ec39-4503-9522-2e115c296de4.png)

**Comment by dnk8n** [comment]
Thanks very much. I applied your advice here - https://github.com/dnk8n/tech-talk/commit/1e9206b2110a67ceceb531c3c28ba68b31e9b1bc

One thing I noticed is that the logout button isn't working as intended. And I guess, although on the backend we have permission to change avatar, the tutorial doesn't actually go into that. But I think I saw some instructions elsewhere on your website on how to use Hasura-storage.

Appreciate your support.

Where I got confused was that for some reason I thought we were replacing the initial user provider... not sure where I got that idea from but it stuck because I repeated it (initially I did the react tutorial).

**Comment by dnk8n** [comment]
For Signout I did have to make the following change - https://github.com/dnk8n/tech-talk/commit/05f10dc752a53643015647f94eedab2b33534f44

**Comment by elitan** [comment]
Following the code example in the guide also works:

<img width="825" alt="CleanShot 2022-06-06 at 07 34 35@2x" src="https://user-images.githubusercontent.com/331818/172101145-8a92835d-d440-44f8-bf86-814483def52f.png">

**Comment by elitan** [comment]
We haven't received any other feedback about the docs so we assume all is good for now.
