### ISSUE TITLE
Denote whether User is new or existing on SignInResponse when using SMS auth

### ISSUE THREAD

**Issue by elleryfamilia** [nhost/nhost#726]
When using SMS authentication, it's impossible to know if the user who was just signed in was just added as a new user or if it already existed in the database. That information would help route them to either the application (they're just logging in) or to a second form to collect additional information. This will save one trip to the server.

**Comment by elitan** [comment]
I would probably keep that kind of information in a separate table, instead of relying on if the user was recently created or not.

Imagine the following:

What if someone signs in (first time) but then have to go and close the tab (no additional information collected). The second time the user signs in they should still be redirected to the second form to fill in the additional information.

**Comment by elleryfamilia** [comment]
Yea I thought of that after posting the issue.

**Comment by elitan** [comment]
I'll close this issue for now. I think it's better to keep that kind of info in the database, for the use case you mentioned.

I'd be happy to re-open the issue if someone thing this deserves more attention.
