### ISSUE TITLE
 NhostNextProvider bundle size is large

### ISSUE THREAD

**Issue by mjerjawi** [nhost/nhost#751]
hello everyone, is there any way to reduce the JS size when adding NhostNextProvider with Next.js it adds around 200Kb

![First_load_js](https://user-images.githubusercontent.com/68725483/175786679-dbefeed1-cf9c-4309-bdf3-1700d3c1702a.png)

**Comment by hajek-raven** [comment]
This is very problematic for presentational websites. For now I just use SWR insted of NHost sdk.

I tried to investigate this issue with bundle-analyzed. According to some StackOverflows it's because somewhere in the code, nhost imports server-side intended nodejs library. I couldn't find it so my suspicion is that some dependency imports this code.
