### ISSUE TITLE
Storage: useFileUpload() fails due to unnique contraint violation on storage.files

### ISSUE THREAD

**Issue by foolish-works** [nhost/nhost#865]
I'm unable to call useFileUpload hook several times without refreshing the browser. The upload works fine with file id being unique only for the first time. From the second time, the API throws a unique constraint violation error on storage.files. This works all fine when I try to refresh the browser and call the hook. The hook also doesn't use the custom id value when passed along.

PS: I'm using the Cloud version of nhost

**Comment by elitan** [comment]
Could you share some code?

Do you provide an `id` when uploading?

If yes: Do you generate a unique id for every new upload?
if no: Very strange. The database should generate a unique `id` for you automatically.

**Comment by foolish-works** [comment]
```
const { upload, isUploading, isError, progress } = useFileUpload();

const uploadFile = async (file: File) => {
	const uploadResponse = await upload({ file, bucketId: CUSTOM_BUCKET });
}
```

_uploadFile()_ called the second time does nothing. No API call was seen to upload a file.

**Comment by ammarfaris** [comment]
> ```
> const { upload, isUploading, isError, progress } = useFileUpload();
> 
> const uploadFile = async (file: File) => {
> 	const uploadResponse = await upload({ file, bucketId: CUSTOM_BUCKET });
> }
> ```
> 
> 
>      
>   
> 
> _uploadFile()_ called the second time does nothing. No API call was seen to upload a file.
> 
> 
> I did try passing the id as part of the function call, didn't work any different.

Experiencing the same thing with useFileUpload hook (when trying to upload the second time and onwards without refreshing browser)  :(

The nhost-js package works though: `await nhost.storage.upload({ file })` , but the react package with hook seems to be more preferable because get other neat functions like the current  upload `progress` , etc

```
  const {
    add,
    upload,
    cancel,
    isUploaded,
    isUploading,
    progress,
    id,
    bucketId,
    name,
  } = useFileUpload()
```

Additionally, I hope that the react hook supports uploading with FormData too (instead of just File format). Thank you!
