### ISSUE TITLE
Import tool for importing users from Firebase Auth (or other providers)

### ISSUE THREAD

**Issue by spakanati** [nhost/nhost#962]
Per Discord discussion, it may be useful for Nhost to provide a tool for importing users from other services similar to what [Supabase has](https://supabase.com/docs/guides/migrations/firebase-auth). According to Johan, the way Supabase imports passwords (using middleware) is probably not possible with the way Nhost is currently set up, but he asked me to create this issue.

Repo to look at for inspiration: https://github.com/supabase-community/firebase-to-supabase/tree/main/auth

At the least, a detailed guide about how to import users from other auth services would be helpful.

**Comment by nbourdin** [comment]
I think it can't be imported easily because the hash algo used in firebase auth is scrypt and the nhost one is bcrypt

**Comment by guicurcio** [comment]
Yes, the hashing algo for the password would be blocker here. 

One solution you could do is to transfer your users in Firebase one-by-one (via a script) by making calls to the auth endpoint. That is, given a dataset of your users in Firebase you'd call your auth endpoint in Nhost adding a given user (plus any metadata you'd like) then when any user connects you would prompt them to reset their password (dismissing their firebase password).

**Comment by elitan** [comment]
I see three alternatives:

## 1. Automatic migration with a custom script

Similar to Auth0: https://auth0.com/docs/manage-users/user-migration/configure-automatic-migration-from-your-database#configure-scripts

1. User signed in
2. if the user is not in the database, Auth checks if the user is in the old database (e.g. Firebase)
3. If it is and the password is correct, Auth creates the user in Nhost (with the correct password).

This solution can be generic to any old database but require developers to provide their own script to check if the user is in the old database. We could maybe leverage an endpoint (serverless function) for this.

This solution requires nothing from end users.

## 2. Export/Import users without password

Another solution is simply exporting the users from the old database and importing them into Nhost. If the password hash algorithm differs (as is the case between Firebase and Nhost), users must always reset their password at Nhost before they can sign in again.

What Nhost could do to help is to have a special flag in the database. Nhost could then return something like "user has been migrated and need to reset their password" instead of a generic "incorrect password" when the user tries to sign in.
