### ISSUE TITLE
GraphQL Engine metadata is inconsistent with database

### ISSUE THREAD

**Issue by FostersData** [nhost/nhost#966]
I just created a new Nhost project, installed the CLI and linked a local project to the new hosted project.

Starting the local dev environment with `nhost up` starts fine but opens to http://localhost:9695/console/settings/metadata-status?is_redirected=true with the error message that `GraphQL Engine metadata is inconsistent with database`.

![image](https://user-images.githubusercontent.com/68621265/192641000-4f493ce4-a119-47e7-8e6a-fa57a98e9cdb.png)

These aren't computed fields, but might be related to https://github.com/nhost/nhost/issues/854? 

I'm on Windows 11 and WSL2 if it's relevant.

**Comment by Nico-L** [comment]
Hello same here, but with a project existing for several months. Every was working fine up to yesterday and I did not touched the tables causing the errors. Could it be linked to the new features on the nhost dashborad?
![image](https://user-images.githubusercontent.com/11961129/192704083-e24302eb-2fa3-406e-989e-2b2065033ab3.png)

**Comment by KristofferEriksson** [comment]
I have the same problem

**Comment by osseonews** [comment]
We also get this error. It's actually thrown in the Hasura Console, in the MetaData Status area.

**Comment by plmercereau** [comment]
Hello,
We are working on solving the issue and will keep you updated.
In the meantime, there is no risk in dropping the two above inconsistencies.

**Comment by nunopato** [comment]
@Nico-L your issue should be easy to solve if you update the CLI to its latest version, `v0.8.3`. Re-running the latest version should remove those 2 tables (`user_authenticators` and `authenticators`) from the metadata files, and a subsequent push should fix those in production as well.

@FostersData Your issue is the inverse. It seems to me that you are already running the latest version which uses the latest renamed tables (`user_authenticators` was renamed to `user_security_keys` and `authenticators` was renamed to `security_keys`). This seems to be one of those instances where the Hasura console gets out of sync with what is in the database. Could you make sure that those tables actually exist in the database? 
1. `psql postgres://postgres:postgres@localhost:5432/postgres`
2. \dt auth.* (this should get you the list of tables in the `auth` schema)

If they are there, please use the Hasura console to delete the inconsistencies and/or reload metadata (check `Reload all databases`)

@KristofferEriksson @osseonews please also confirm if this is still an issue for you.

**Comment by FostersData** [comment]
It's still called `user_authenticators` for me - can I just rename that in the Hasura console or do I need to run an `nhost` CLI command?

**Comment by FostersData** [comment]
I was on `v0.8.1`, confirmed that some combination of upgrading to `v0.8.3`, deleting the `.nhost` folder and running `nhost up` again fixed the issue!

**Comment by elitan** [comment]
Excellent. Closing this issue for now.
